# CONFIGURATION FILE
# to be customized befor running the scripts
path = "C:/Users/claud/OneDrive - UNICEF/ARR/ARR" # the path on your system from where you will be launching the code

# load sources file name and sheet name
combiner_cr = "cr_clean.xlsx" # the excel file from the combiner flow
combiner_pr = "pr_clean.xlsx" # the excel file from the combiner flow
grants_db = "grants_db.csv" # this file is coming from the GMS
mne_approval = "ARR24 MnE Reports approval.xlsx" # this file will change next year (retired in 2024)
sheet_mne = "MnE reports approval" # depending on the file above
codes = "analysis_codes.xlsx" # this is already downloaded from the github

# yearly parameters
report_year = "2024" # "YYYY" year parameter
previous_report_year = "2023" # "YYYY" year parameter
source_cr = "CR24" # "Source of data" parameter (CR22, CR21, etc etc)
source_pr = "PR24" # "Source of data" parameter (PR22, PR21, etc etc)
report_year_number = 2024
annual = 8 # define variables (they are encoded in numerical form sequentially)
cumulative = 9 # (2022 is 4 and 5, 2023 will be 6 and 7, etc etc)
past_annual = 6 # past year; same approach as above
past_cumulative = 7 # past year; same approach as above
ex_com_approval_date_cutoff = "2024-01-01"
